/* eslint-disable @typescript-eslint/no-empty-object-type */
// Generated by Xata Codegen 0.30.1. Please do not edit.


import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,

} from "@xata.io/client";



export type DatabaseSchema = {};

const DatabaseClient = buildClient();
console.log("XATA_API_KEY:", process.env.XATA_API_KEY);


const defaultOptions = {
  databaseURL:
    "https://Asifahmed-sahil-s-workspace-vn637a.eu-central-1.xata.sh/db/streemly",
    apiKey:process.env.XATA_API_KEY,
    branch:"main"
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options });
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
